name: node_js CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [16]
        npm: [8.5.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install -g npm@${{ matrix.npm }}

    - run: npm install -g npm@${{ matrix.npm }}
    
    - name: Install dependencies
      run: npm ci

    - name: Package lock check
      run: make validate-no-uncommitted-package-lock-changes

    - name: Extract i18n
      run: npm run i18n_extract

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build

    - name: Run Allowlist Audit
      run: npm run audit:allowlisted
